# docker network create -d macvlan --subnet=192.168.11.0/24 --gateway=192.168.11.1 -o parent=ens34 macvlan


services:
  macvlan:
    container_name: macvlan
    image: mritd/alpine
    restart: always
    command: /bin/bash -c "sleep infinity"
    networks:
      macvlan:
        ipv4_address: 192.168.11.33
networks:
  macvlan:
    external: true
