
services:
  nfs:
    image: erichough/nfs-server:2.2.1
    container_name: nfs_server
    restart: unless-stopped
    environment:
    #  - NFS_VERSION=4
    #  - NFS_DISABLE_VERSION_3=1
      - NFS_LOG_LEVEL=DEBUG
    volumes: 
      - ./exports:/etc/exports
      - /lib/modules:/lib/modules:ro
      - /data/nfs:/data
    cap_add:
      - SYS_ADMIN
      - SYS_MODULE
    security_opt:
      - apparmor=erichough-nfs
    ports:
      - "111:111"
      - "111:111/udp"
      - "2049:2049"
      - "2049:2049/udp"
      - "32765:32765"
      - "32765:32765/udp"
      - "32767:32767"
      - "32767:32767/udp"
