services:
  caddy:
    image: mritd/caddy
    container_name: caddy
    restart: unless-stopped
    networks:
      - caddy
    env_file: .env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone
      - ./conf:/etc/caddy
      - config:/config
      - data:/data
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
      - "2443:2443"

networks:
  caddy:
    name: caddy
    external: true

volumes:
  config:
  data:
