# kibana.yaml: https://raw.githubusercontent.com/elastic/kibana/master/config/kibana.yml

services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.9.2
    restart: unless-stopped
    ports:
      - 5601:5601
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
