
services:
  pebble:
    image: letsencrypt/pebble:latest
    container_name: pebble
    restart: unless-stopped
    environment:
      # TODO(@cpu): Delete this explicit GODEBUG env var once Pebble is built
      # with Go 1.13.x which defaults TLS 1.3 to on
      GODEBUG: "tls13=1"
    ports:
      - 14000:14000  # HTTPS ACME API
      - 15000:15000  # HTTPS Management API
    command: ["pebble","-strict","-config","/test/config/pebble-config.json","-dnsserver","114.114.114.114:53"]
