
services:
  coredns:
    image: coredns/coredns:1.5.0
    container_name: coredns
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./Corefile:/etc/Corefile
      - ./hosts:/etc/hosts
    command: -conf /etc/Corefile
