
services:
  grafana:
    image: grafana/grafana:8.3.3
    container_name: grafana
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      GF_RENDERING_SERVER_URL: 'http://grafana-image-renderer:8081/render'
      GF_RENDERING_CALLBACK_URL: 'http://grafana:3000/'
      GF_LOG_FILTERS: 'rendering:info'
    volumes:
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
      - etc:/etc/grafana
      - data:/var/lib/grafana
    ports:
      - "3000:3000"
  grafana-image-renderer:
    image: grafana/grafana-image-renderer:3.3.0
    container_name: grafana-image-renderer
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    volumes:
#      - /etc/timezone:/etc/timezone:ro
#      - /etc/localtime:/etc/localtime:ro
      - ./config.json:/usr/src/app/config.json
volumes:
  etc:
  data:
