
services:
  uptime:
    image: louislam/uptime-kuma
    container_name: uptime
    restart: unless-stopped
    networks:
      - caddy
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone
      - data:/app/data

networks:
  caddy:
    name: caddy
    external: true

volumes:
  data:
