
services:
  runner:
    container_name: runner
    image: gitlab/gitlab-runner:alpine3.14-v14.5.1
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.toml:/etc/gitlab-runner/config.toml
