
services:
  activemq:
    image: rmohr/activemq:5.15.4-alpine
    container_name: activemq
    restart: unless-stopped
    volumes: 
      - data:/data
    ports:
      - "1883:1883"
      - "5672:5672"
      - "8161:8161"
      - "61613:61613"
      - "61614:61614"
      - "61616:61616"
volumes:
  data:
