

services:
  headscale:
    container_name: headscale
    image: headscale/headscale
    restart: unless-stopped
    networks:
      - caddy
    ports:
      - 3456:3456/tcp
      - 3456:3456/udp
    volumes:
      - ./conf:/etc/headscale
      - data:/var/lib/headscale
    command: ["headscale", "serve"]
networks:
  caddy:
    name: caddy
    external: true
volumes:
  data:
