
services:
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx
    restart: unless-stopped
    networks:
      - nginx
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./log:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
networks:
  nginx:
    external:
      name: nginx
