
services:
  kafka-manager:
    image: mritd/kafka-manager
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      - ZK_HOSTS
      - KAFKA_MANAGER_AUTH_ENABLED
      - KAFKA_MANAGER_LDAP_ENABLED
      - KAFKA_MANAGER_LDAP_SSL
      - KAFKA_MANAGER_LDAP_SERVER
      - KAFKA_MANAGER_LDAP_PORT
      - KAFKA_MANAGER_LDAP_USERNAME
      - KAFKA_MANAGER_LDAP_PASSWORD
      - KAFKA_MANAGER_LDAP_SEARCH_BASE_DN
      - KAFKA_MANAGER_LDAP_SEARCH_FILTER
      - KAFKA_MANAGER_LDAP_CONNECTION_POOL_SIZE
