services:
  tgupdater:
    image: mritd/tgupdater
    container_name: tgupdater
    restart: unless-stopped
    env_file: .env
    volumes:
      - /etc/timezone:/etc/timezone
      - data:/data
#   command: ["bash","-c","sleep 9999999"]
volumes:
  data:
