
services:
  mattermost:
    image: mritd/mattermost:5.0.0
    restart: always
    container_name: mattermost
    volumes:
      - data:/data
      - ./config.json:/mattermost/config/config.json
    links:
      - mysql
    ports:
      - 8065:8065
  mysql:
    image: mysql:5.7.17
    restart: always
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD
volumes:
  data:
  mysql:
