
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    container_name: logstash
    restart: unless-stopped
    network_mode: "host"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone
      - /data/logstash:/data
      - ./config:/usr/share/logstash/config
      - ./pipeline:/usr/share/logstash/pipeline
