
services:
  postgres:
    image: postgres:11.4-alpine
    container_name: postgres
    restart: always
    volumes: 
      - data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

volumes:
  data:
