
services:
  influxdb:
    image: influxdb:1.7-alpine
    container_name: influxdb
    restart: unless-stopped
    volumes:
      - data:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "8083:8083"
      - "2003:2003"
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_DB
      - INFLUXDB_ADMIN_USER
      - INFLUXDB_ADMIN_PASSWORD
      - INFLUXDB_USER
      - INFLUXDB_USER_PASSWORD
volumes:
  data:
