
services:
  notibot:
    image: mritd/notibot
    container_name: notibot
    restart: unless-stopped
    networks:
      - caddy
    env_file: .env
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone
networks:
  caddy:
    name: caddy
    external: true
