
services:
  mongo:
    image: mongo:5
    container_name: mongo
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - data:/data
    ports:
      - "27017:27017"
volumes:
  data:
