
services:
  hitchhiker:
    image: mritd/hitchhiker:v0.13
    container_name: hitchhiker
    restart: unless-stopped
    volumes: 
      - ./conf/appconfig.json:/Hitchhiker/appconfig.json
      - project:/Hitchhiker/build/global_data/project
      - backup:/Hitchhiker/build/backup
      - logs:/Hitchhiker/build/logs
    ports: 
      - "8300:443" 
      - "11010:11010"
  hitchhiker-mysql:
    image: mysql:5.7
    container_name: hitchhiker-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=hitchhiker888
      - MYSQL_DATABASE=hitchhiker-prod
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/hitchhiker.cnf
      - mysql:/var/lib/mysql
volumes:
  mysql:
  project:
  backup:
  logs:
