services:
  mritd_com:
    image: mritd/mritd.com
    container_name: mritd_com
    restart: unless-stopped
    networks:
      - caddy
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /etc/timezone:/etc/timezone

networks:
  caddy:
    name: caddy
    external: true
